# Generated by Django 6.0.4 on 2026-05-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_skrodatransaction_delivery_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skrodatransaction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('negotiation', 'Negotiation'), ('agreed', 'Agreed'), ('funded', 'Funded'), ('shipped', 'Shipped'), ('agent_received', 'Agent Received'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('agent_unavailable', 'Agent Unavailable')], default='draft', max_length=30),
        ),
    ]
