# Generated by Django 6.0.4 on 2026-04-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_store_owner_storestaff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='currency_symbol',
            field=models.CharField(default='GHS', max_length=10),
        ),
    ]
