# Generated by Django 6.0.4 on 2026-04-17 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_store_currency_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_partial_payment', models.BooleanField(default=False)),
                ('allow_credit', models.BooleanField(default=False)),
                ('min_deposit_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('preorder_enabled', models.BooleanField(default=True)),
                ('preorder_payment_policy', models.CharField(choices=[('upfront', 'Full Payment Upfront'), ('deposit', 'Deposit Required'), ('on_delivery', 'Pay on Delivery/Pickup')], default='on_delivery', max_length=20)),
                ('preorder_deposit_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('preorder_expected_days', models.PositiveIntegerField(default=7)),
                ('preorder_welcome_message', models.TextField(blank=True)),
                ('preorder_whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number with country code, e.g. 233244000000', max_length=20)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.store')),
            ],
        ),
    ]
