# Generated by Django 6.0.4 on 2026-04-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_storesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='preorder_all_products',
            field=models.BooleanField(default=True, help_text='Show all active products in preorder catalog'),
        ),
    ]
