# Generated by Django 6.0.4 on 2026-04-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_storesettings_preorder_all_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='manager_can_manage_shipments',
            field=models.BooleanField(default=False, help_text='Allow store managers to access shipment management'),
        ),
    ]
