# Generated by Django 6.0.4 on 2026-04-24 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_storesettings_manager_can_manage_shipments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storestaff',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='storestaff',
            constraint=models.UniqueConstraint(condition=models.Q(('pin__gt', '')), fields=('store', 'pin'), name='unique_store_pin_when_set'),
        ),
    ]
