# Generated by Django 6.0.4 on 2026-04-18 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_storesettings_preorder_all_products'),
        ('inventory', '0005_product_preorder_lead_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('salary', 'Staff Salary'), ('transport', 'Transportation'), ('marketing', 'Marketing'), ('breakage', 'Breakages'), ('expiry', 'Expired Products'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('date', models.DateField()),
                ('product_qty', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='inventory.product')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_recorded', to='core.storestaff')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.store')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
