# Generated by Django 6.0.4 on 2026-04-24 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='shipments.shipment'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('salary', 'Staff Salary'), ('transport', 'Transportation'), ('freight', 'Freight'), ('customs', 'Customs'), ('clearing', 'Clearing'), ('marketing', 'Marketing'), ('breakage', 'Breakages'), ('expiry', 'Expired Products'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('other', 'Other')], max_length=20),
        ),
    ]
