# Generated by Django 6.0.4 on 2026-04-24 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_storesettings_preorder_all_products'),
        ('inventory', '0007_product_color_options_product_has_color_variants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=100)),
                ('shipping_company', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('AIR', 'Air Freight'), ('SEA', 'Sea Freight')], default='SEA', max_length=3)),
                ('status', models.CharField(choices=[('WAREHOUSE', 'At Origin Warehouse'), ('TRANSIT', 'In Transit'), ('PORT', 'At Ghana Port'), ('CUSTOMS', 'At Customs'), ('ARRIVED', 'Ready for Pickup'), ('DELIVERED', 'Delivered')], default='WAREHOUSE', max_length=15)),
                ('origin', models.CharField(default='China', max_length=100)),
                ('destination', models.CharField(default='Ghana', max_length=100)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('estimated_arrival', models.DateField(blank=True, null=True)),
                ('actual_arrival', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='shipments/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('store', 'tracking_number')},
            },
        ),
        migrations.CreateModel(
            name='ShipmentPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_code', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_received', models.BooleanField(default=False)),
                ('is_fragile', models.BooleanField(default=False)),
                ('is_stocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='shipments.shipment')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
            options={
                'ordering': ['created_at', 'package_code'],
                'unique_together': {('shipment', 'package_code')},
            },
        ),
        migrations.CreateModel(
            name='ShipmentPackageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_quantity', models.PositiveIntegerField()),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipmentpackage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_package_items', to='inventory.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='shipments.shipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
