# Generated by Django 6.0.4 on 2026-04-17 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category_expiry_warning_days_product_barcode_and_more'),
        ('preorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='customer_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='preorder',
            name='customer_whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='preorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preorder_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='preorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='preorderitem',
            name='item_description',
            field=models.CharField(help_text='Product name snapshot or custom request', max_length=500),
        ),
    ]
