# Generated by Django 6.0.4 on 2026-04-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preorders', '0002_preorder_customer_city_preorder_customer_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='pickup_code',
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='preorder',
            name='pickup_code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='pickup_code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='pickup_code_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preorderitem',
            name='selected_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='preorderitem',
            name='selected_size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
