# Generated by Django 6.0.4 on 2026-04-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_product_supplier_suppliertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expiry_warning_days',
            field=models.PositiveIntegerField(default=30, help_text='Days before expiry to show warning'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
