# Generated by Django 6.0.4 on 2026-04-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category_expiry_warning_days_product_barcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_for_preorder',
            field=models.BooleanField(default=False),
        ),
    ]
