# Generated by Django 6.0.4 on 2026-04-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_available_for_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preorder_lead_days',
            field=models.PositiveIntegerField(blank=True, help_text='Expected days to fulfil a preorder for this product', null=True),
        ),
    ]
