# Generated by Django 6.0.4 on 2026-04-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_preorder_lead_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sku_prefix',
            field=models.CharField(blank=True, help_text='2-4 letter prefix for SKUs, e.g. BEV, CLN', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='False if stock was taken on credit from supplier'),
        ),
    ]
