# Generated by Django 6.0.4 on 2026-04-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_category_sku_prefix_product_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_options',
            field=models.TextField(blank=True, help_text='One color per line or comma-separated'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_color_variants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='has_size_variants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_description',
            field=models.TextField(blank=True, help_text='Shown to customers on the preorder page'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_options',
            field=models.TextField(blank=True, help_text='One size per line or comma-separated'),
        ),
    ]
