# Generated by Django 6.0.4 on 2026-04-19 09:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_storesettings_preorder_all_products'),
        ('inventory', '0006_category_sku_prefix_product_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('planned_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.storestaff')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_plans', to='core.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_product_name', models.CharField(blank=True, max_length=300)),
                ('planned_qty', models.PositiveIntegerField(default=1)),
                ('estimated_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier_name', models.CharField(blank=True, max_length=300)),
                ('supplier_location', models.CharField(blank=True, max_length=300)),
                ('current_stock', models.IntegerField(default=0)),
                ('actual_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('available_for_preorder', models.BooleanField(default=False)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_items', to='inventory.product')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.procurementplan')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
